platform :ios, '7.1'
inhibit_all_warnings!

pod 'AFNetworking'
pod 'CocoaLumberjack'
pod 'google-plus-ios-sdk'
pod 'libextobjc'
pod 'BlocksKit'
pod 'Mantle'
pod 'PromiseKit'
pod 'Typhoon'
pod 'Maris'
pod 'CompactConstraint'

target 'GBooksReaderTests', :exclusive => true do
  pod 'Kiwi'
  pod 'OHHTTPStubs'
end
